Update reeeeadme
dendi239/algorithms-data-structures pull request #2
Opened 2020-04-30 23:34 UTC by ViktoriiaKovalova

⊂(◉‿◉)つ⊂(◉‿◉)つ⊂(◉‿◉)つ

2020-04-30 23:50 UTC, dendi239 requested changes

2020-04-30 23:50 UTC, dendi239 commented on algebra/README.md
> +It supports any modulo you providde, but if you need to divide reisudes one by another, you'll need to ensure that `gcd(modulo, denominator) = 1`.
Fix typo in "providde" as well, please

2020-05-01 00:05 UTC, ViktoriiaKovalova commented on algebra/README.md
> +It supports any modulo you providde, but if you need to divide reisudes one by another, you'll need to ensure that `gcd(modulo, denominator) = 1`.
Okk

2020-05-01 00:06 UTC, dendi239 approved these changes

2020-05-01 00:07 UTC, merged